Güncel 2.2/ShopApp/ShopApp.WebUI/Models/ResultMessage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShopApp.WebUI.Models
{
    public class ResultMessage
    {
        public string Title { get; set; }
        public string Message { get; set; }
        public string Css { get; set; } 
    }
}

Güncel 2.2/ShopApp/ShopApp.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IyzipayCore;
using IyzipayCore.Model;
using IyzipayCore.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShopApp.Business.Abstract;
using ShopApp.Entities;
using ShopApp.WebUI.Identity;
using ShopApp.WebUI.Models;

namespace ShopApp.WebUI.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartService _cartService;
        private IOrderService _orderService;
        private UserManager<ApplicationUser> _userManager;

        public CartController(IOrderService orderService, ICartService cartService, UserManager<ApplicationUser> userManager)
        {
            _orderService = orderService;
            _cartService = cartService;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));
            return View(new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.Id,
                    ProductId = i.Product.Id,
                    Name = i.Product.Name,
                    Price = (decimal)i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity
                }).ToList()
            });
        }

        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity)
        {
            _cartService.AddToCart(_userManager.GetUserId(User), productId, quantity);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteFromCart(int productId)
        {
            _cartService.DeleteFromCart(_userManager.GetUserId(User), productId);
            return RedirectToAction("Index");
        }

        public IActionResult Checkout()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            var orderModel = new OrderModel();

            orderModel.CartModel = new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.Id,
                    ProductId = i.Product.Id,
                    Name = i.Product.Name,
                    Price = (decimal)i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity
                }).ToList()
            };

            //orderModel.PaymentTypes = EnumPaymentTypes.CreditCart;

            ViewBag.PaymentTypes = Enum.GetValues(typeof(EnumPaymentTypes));

            return View(orderModel);
        }

        [HttpPost]
        public IActionResult Checkout(OrderModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var cart = _cartService.GetCartByUserId(userId);

                model.CartModel = new CartModel()
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(i => new CartItemModel()
                    {
                        CartItemId = i.Id,
                        ProductId = i.Product.Id,
                        Name = i.Product.Name,
                        Price = (decimal)i.Product.Price,
                        ImageUrl = i.Product.ImageUrl,
                        Quantity = i.Quantity
                    }).ToList()
                };



                var payment = PaymentProcess(model);
                if (payment.Status == "success")
                {
                    SaveOrder(model, payment, userId);
                    ClearCart(cart.Id.ToString());
                    return View("Success");
                }
                if (model.PaymentTypes!=0)
                {
                    SaveOrder(model, payment, userId);
                    ClearCart(cart.Id.ToString());
                    return View("Success");

                }
                
            }

            ViewBag.PaymentTypes = Enum.GetValues(typeof(EnumPaymentTypes));
            return View(model);
        }


        //public IActionResult GetPaymentTypeValue(int id)
        //{
        //    return Json(id);
        //}


        private void SaveOrder(OrderModel model, Payment payment, string userId)
        {
            var order = new Order();

            order.OrderNumber = new Random().Next(111111, 999999).ToString();
            order.OrderState = EnumOrderState.waiting;
            order.PaymentTypes = model.PaymentTypes;
            order.PaymentId = payment.PaymentId;
            order.ConversationId = payment.ConversationId;
            order.OrderDate = DateTime.Now;
            order.FirstName = model.FirstName;
            order.LastName = model.LastName;
            order.Email = model.Email;
            order.Phone = model.Phone;
            order.Address = model.Address;
            order.UserId = userId;

            foreach (var item in model.CartModel.CartItems)
            {
                var orderitem = new OrderItem()
                {
                    Price = item.Price,
                    Quantity = item.Quantity,
                    ProductId = item.ProductId,
                    //Name = item.Name
                };
                order.OrderItems.Add(orderitem);
            }
            _orderService.Create(order);
        }

        private void ClearCart(string cartId)
        {
            _cartService.ClearCart(cartId);
        }

        private Payment PaymentProcess(OrderModel model)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-fluMRB1NjmuwWfflqj4zjUH2a6hy9xfp";
            options.SecretKey = "sandbox-Xcz1WgPvmm1aBX3rxt1b1Ifa6O399tK8";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";

            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = Guid.NewGuid().ToString();
            request.Price = model.CartModel.TotalPrice().ToString().Split(",")[0]; ;
            request.PaidPrice = model.CartModel.TotalPrice().ToString().Split(",")[0]; ;
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = model.CartModel.CartId.ToString();
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth = model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.Cvv;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;

            //paymentCard.CardHolderName = "John Doe";
            //paymentCard.CardNumber = "5528790000000008";
            //paymentCard.ExpireMonth = "12";
            //paymentCard.ExpireYear = "2030";
            //paymentCard.Cvc = "123";

            Buyer buyer = new Buyer();
            buyer.Id = "BY789";
            buyer.Name = "John";
            buyer.Surname = "Doe";
            buyer.GsmNumber = "+905350000000";
            buyer.Email = "email@email.com";
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            buyer.Ip = "85.34.78.112";
            buyer.City = "Istanbul";
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;

            Address shippingAddress = new Address();
            shippingAddress.ContactName = "Jane Doe";
            shippingAddress.City = "Istanbul";
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

            Address billingAddress = new Address();
            billingAddress.ContactName = "Jane Doe";
            billingAddress.City = "Istanbul";
            billingAddress.Country = "Turkey";
            billingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            billingAddress.ZipCode = "34742";
            request.BillingAddress = billingAddress;

            List<BasketItem> basketItems = new List<BasketItem>();
            BasketItem basketItem;

            foreach (var item in model.CartModel.CartItems)
            {
                basketItem = new BasketItem();
                basketItem.Id = item.ProductId.ToString();
                basketItem.Name = item.Name;
                basketItem.Category1 = "Phone";
                basketItem.ItemType = BasketItemType.PHYSICAL.ToString();
                basketItem.Price = item.Price.ToString().Split(",")[0];

                basketItems.Add(basketItem);
            }

            request.BasketItems = basketItems;

            return Payment.Create(request, options);

        }

        public IActionResult GetOrders()
        {
            var orders = _orderService.GetOrders(_userManager.GetUserId(User)).OrderByDescending(x => x.OrderDate); 
            var orderListModel = new List<OrderListModel>();
            OrderListModel orderModel;

            foreach (var order in orders)
            {
                orderModel = new OrderListModel();

Güncel 2.2/ShopApp/ShopApp.WebUI/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShopApp.Business.Abstract;
using ShopApp.Entities;
using ShopApp.WebUI.Models;

namespace ShopApp.WebUI.Controllers
{
    public class ShopController : Controller
    {
        private IProductService _productService;
        public ShopController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails((int)id);
            if (product == null)
            {
                return NotFound();
            }
            return View(new ProductDetailsModel()
            {
                Product = product,
                Categories = product.ProductCategories.Select(i => i.Category).ToList()
            });
        }

        //products/telefon?page=2
        public IActionResult List(string category, int page = 1)
        {
            const int pageSize = 6; //bir sayfada kaç ürün gözükecek?
            return View(new ProductListModel()
            {
                Products = _productService.GetProductsByCategory(category, page, pageSize),
                PagingInfo = new PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = _productService.GetCountByCategory(category),
                    CurrentCategory = category
                }
            });
        }

        public IActionResult Search(string q)
        {
            var productListModel =  View(new ProductListModel()
            {
                Products = _productService.GetSearchResult(q)
            });

            return View(productListModel);
        }
    }
}

Güncel 2.2/ShopApp/ShopApp.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="~/User/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/User/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/User/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/User/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/User/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/User/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/User/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/User/css/style.css" type="text/css">

    
    <meta name="viewport" content="width=device-width" />

    @await Html.PartialAsync("_LayoutCssPartial")

    <title>ShopApp</title>
</head>
<body>
    <partial name="_navbar" />


    <div class="container-fluid pt-25 mb-5">

        @if (TempData["message"] != null)
        {
            <partial name="_resultmessage" model="@(TempData.Get<ResultMessage>("message"))" />
        }


        @RenderBody()
    </div>


    @await Html.PartialAsync("_LayoutJsPartial")
    @RenderSection("Scripts", false)



    /
    <!-- Js Plugins -->
    <script src="~/Userjs/jquery-3.3.1.min.js"></script>
    <script src="~/Userjs/bootstrap.min.js"></script>
    <script src="~/Userjs/jquery.nice-select.min.js"></script>
    <script src="~/Userjs/jquery-ui.min.js"></script>
    <script src="~/Userjs/jquery.slicknav.js"></script>
    <script src="~/Userjs/mixitup.min.js"></script>
    <script src="~/Userjs/owl.carousel.min.js"></script>
    <script src="~/Userjs/main.js"></script>

</body>
</html>

Güncel 2.2/ShopApp/ShopApp.WebUI/Views/Shared/_navbar.cshtml
<div id="preloder">
    <div class="loader"></div>
</div>
<div class="humberger__menu__overlay"></div>
<div class="humberger__menu__wrapper">
    <div class="humberger__menu__logo">
        <a href="#"><img src="~/User/img/logo3.png" alt=""></a>
    </div>
    
    <div class="humberger__menu__widget">
        <div class="header__top__right__language">
            <img src="~/User/img/bayrak.png" alt="">
            <div>Türkçe</div>
            <span class="arrow_carrot-down"></span>
            <ul>
                <li><a href="#">Türkçe</a></li>
            </ul>
        </div>
        <div class="header__top__right__auth">

            @if (User.Identity.IsAuthenticated)
            {
                <div class="header__top__right__social">

                    @*<a asp-controller="Account" asp-action="Manage">
                        @User.Identity.Name
                    </a>*@
                    <a asp-controller="Account" asp-action="Logout"><i class="fa fa-user"></i>Çıkış Yap</a>
                </div>
            }
            else
            {
                <div class="header__top__right__social">
                    <a asp-controller="Account" asp-action="Login"><i class="fa fa-user"></i> Giriş Yap</a>
                    <a asp-controller="Account" asp-action="Register"><i class="fa fa-user"></i> Kayıt Ol</a>
                </div>
            }
        </div>
    </div>
    <nav class="humberger__menu__nav mobile-menu">
        <ul>
            <li class="active"><a asp-controller="Home" asp-action="Index">Ana Sayfa</a></li>
            <li><a asp-controller="Shop" asp-action="List">Ürünler</a></li>
            @if (User.Identity.IsAuthenticated)
            {
                <li>
                    <a href="#">Sepetim</a>
                    <ul class="header__menu__dropdown">
                        <li><a asp-controller="Cart" asp-action="Index">Sepetim</a></li>
                        <li><a asp-controller="Cart" asp-action="GetOrders">Siparişlerim</a></li>
                    </ul>
                </li>
                if (User.IsInRole("admin"))
                {

                    <li>
                        <a href="#">Admin</a>
                        <ul class="header__menu__dropdown">
                            <li><a asp-controller="Admin" asp-action="Index">Admin Paneli</a></li>
                            <li><a asp-controller="Admin" asp-action="ProductList">Ürünler</a></li>
                            <li><a asp-controller="Admin" asp-action="CreateProduct">Ürün Ekle</a></li>
                            <li><a asp-controller="Admin" asp-action="CategoryList">Kategoriler</a></li>
                            <li><a asp-controller="Admin" asp-action="CreateCategory">Kategori Ekle</a></li>
                            <li><a asp-controller="Admin" asp-action="OrderList">Siparişler</a></li>
                            <li><a asp-controller="Admin" asp-action="UserList">Kullanıcılar</a></li>
                        </ul>
                    </li>
                }
                if (User.IsInRole("kurye"))
                {

                    <li>
                        <a href="#">Kurye İşlemleri</a>
                        <ul class="header__menu__dropdown">
                            <li><a asp-controller="Admin" asp-action="ProductList">Sipariş Durumu</a></li>
                        </ul>
                    </li>
                }
                if (User.IsInRole("kasiyer"))
                {

                    <li>
                        <a href="#">Kasiyer İşlemleri</a>
                        <ul class="header__menu__dropdown">
                            <li><a asp-controller="Admin" asp-action="ProductList">Kasa</a></li>
                        </ul>
                    </li>
                }

            }
        </ul>
    </nav>
    <div id="mobile-menu-wrap"></div>
    
</div>


<header class="header">
    <div class="header__top">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="header__top__left">
                        <ul>
                            <li><i class="fa fa-envelope"></i> deneme@gmail.com</li>
                            <li>Hızlı, güvenilir alışveris.</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="header__top__right">
                        <div class="header__top__right__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                            <a href="#"><i class="fa fa-pinterest-p"></i></a>
                        </div>
                        <div class="header__top__right__language">
                            <img src="~/User/img/bayrak.png" alt="">
                            <div>Türkçe</div>
                            <span class="arrow_carrot-down"></span>
                            <ul>
                                <li><a href="#">Türkçe</a></li>
                            </ul>
                        </div>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <div class="header__top__right__social">

                                <a asp-controller="Account" asp-action="Manage">
                                    @User.Identity.Name
                                </a>
                                <a asp-controller="Account" asp-action="Logout"><i class="fa fa-user"></i>Çıkış Yap</a>
                            </div>
                        }
                        else
                        {
                            <div class="header__top__right__social">
                                <a asp-controller="Account" asp-action="Login"><i class="fa fa-user"></i> Giriş Yap</a>
                                <a asp-controller="Account" asp-action="Register"><i class="fa fa-user"></i> Kayıt Ol</a>
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="header__logo">
                    <a asp-controller="Home" asp-action="Index"><img src="~/User/img/logo3.png" alt="" style="margin-left:30px"></a>
                </div>
            </div>
            <div class="col-lg-6">
                <nav class="header__menu">
                    <ul>
                        <li class="active"><a asp-controller="Home" asp-action="Index">Ana Sayfa</a></li>
                        <li><a asp-controller="Shop" asp-action="List">Ürünler</a></li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a href="#">Sepetim</a>
                                <ul class="header__menu__dropdown">
                                    <li><a asp-controller="Cart" asp-action="Index">Sepetim</a></li>
                                    <li><a asp-controller="Cart" asp-action="GetOrders">Siparişlerim</a></li>
                                </ul>
                            </li>
                            if (User.IsInRole("admin"))
                            {

                                <li>
                                    <a href="#">Admin</a>
                                    <ul class="header__menu__dropdown">
                                        <li><a asp-controller="Admin" asp-action="Index">Admin Paneli</a></li>
                                        <li><a asp-controller="Admin" asp-action="ProductList">Ürünler</a></li>
                                        <li><a asp-controller="Admin" asp-action="CreateProduct">Ürün Ekle</a></li>
                                        <li><a asp-controller="Admin" asp-action="CategoryList">Kategoriler</a></li>
                                        <li><a asp-controller="Admin" asp-action="CreateCategory">Kategori Ekle</a></li>
                                        <li><a asp-controller="Admin" asp-action="OrderList">Siparişler</a></li>
                                        <li><a asp-controller="Admin" asp-action="UserList">Kullanıcılar</a></li>
                                    </ul>
                                </li>
                            }
                            if (User.IsInRole("kurye"))
                            {

                                <li>
                                    <a href="#">Kurye İşlemleri</a>
                                    <ul class="header__menu__dropdown">
                                        <li><a asp-controller="Admin" asp-action="ProductList">Sipariş Durumu</a></li>
                                    </ul>
                                </li>
                            }
                            if (User.IsInRole("kasiyer"))
                            {

                                <li>
                                    <a href="#">Kasiyer İşlemleri</a>
                                    <ul class="header__menu__dropdown">
                                        <li><a asp-controller="Admin" asp-action="ProductList">Kasa</a></li>
                                    </ul>
                                </li>
                            }

                        }
                        <li><a href="./contact.html">İletişim</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3">
                <div class="header__cart">

                    <ul>
                        <li><a asp-controller="Cart" asp-action="Index"><i class="fa fa-shopping-bag"></i> @*<span>@Model.cart</span>*@</a></li>
                    </ul>
                    @if (User.IsInRole("admin"))
                    {
                        <ul>
                            <li><a asp-controller="Admin" asp-action="Index"><i class="btn-sm site-btn text-white">Admin Panel</i> @*<span>@Model.cart</span>*@</a></li>
                        </ul>
                    }
                </div>
            </div>
        </div>
        <div class="humberger__open">
            <i class="fa fa-bars"></i>
        </div>
    </div>

</header>

Güncel 2.2/ShopApp/ShopApp.WebUI/Views/Shared/_product.cshtml
@model Product


<!--<div class="container col-md-4">-->
    @*<div class="card mb-3" style="border-radius:25px">
        
        <div class="featured__item__text">
            <h6><a href="#">@Model.Name</a></h6>
        </div>
        <center><img src="~/img/@Model.ImageUrl " alt="@Model.Name" style="height:200px" width="200" /></center>
        <div class="featured__item__text">
            <h5> <i class="fas fa-lira-sign"></i>@Model.Price</h5>
            <br />
        </div>
        <div class="card-footer text-center">
            <a asp-controller="Shop" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-outline-dark btn-sm " style="border-radius:25px"><i class="fa fa-info-circle"></i>Ürün Detay</a>

            @if (User.Identity.IsAuthenticated)
            {
                <form asp-controller="Cart" asp-action="AddToCart" method="post" style="display:inline;">
                    <input type="hidden" name="productId" value="@Model.Id" />
                    <input type="hidden" name="quantity" value="1" />
                    <button type="submit" class="btn btn-outline-dark btn-sm ml-3" style="border-radius:25px"><i class="fa fa-shopping-cart"></i> Sepete Ekle</button>
                </form>
            }
        </div>
    </div>*@




<!--</div>-->









    <!--<div class="col-md-4  mb-4 mt-4 mb-lg-0">-->
        <!-- Card-->
        <!--<div class="card rounded shadow-sm mb-4" style="border: 8px ridge #7b3200; " >
            <div class="card-body p-4 text-center">
                <img src="~/img/@Model.ImageUrl " alt="@Model.Name"  style="height:300px" width="300"> 
                <h3> <a href="#" class="text-dark">@Model.Name</a></h3>
                <h5> <i class="fas fa-lira-sign"></i>@Model.Price</h5>
                <br />
                <div class="text-center">
                    <a asp-controller="Shop" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-outline-dark btn-sm " style="border-radius:25px"><i class="fa fa-info-circle"></i>Ürün Detay</a>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <form asp-controller="Cart" asp-action="AddToCart" method="post" style="display:inline;">
                            <input type="hidden" name="productId" value="@Model.Id" />
                            <input type="hidden" name="quantity" value="1" />
                            <button type="submit" class="btn btn-outline-dark btn-sm ml-3" style="border-radius:25px"><i class="fa fa-shopping-cart"></i> Sepete Ekle</button>
                        </form>
                    }
                </div>

            </div>
        </div>x""
    </div>-->    
<link href="~/css/cardStyle.css" rel="stylesheet" />
<div class="col-md-4">
    <div class="container-fluid d-flex justify-content-center" >
        <figure class="card card-product-grid card-lg">
            <a asp-controller="Shop" asp-action="Details" asp-route-id="@Model.Id" class="img-wrap" data-abc="true"> <img src="~/img/@Model.ImageUrl " alt="@Model.Name"></a>
            <figcaption class="info-wrap">
                <div class="row">
                    <div class="col-md-9 col-xs-9"> <a href="#" class="title" data-abc="true"><h4>@Model.Name</h4></a> <span class="rated"></span> </div>
                    <div class="col-md-3 col-xs-3">
                        @*<div class="rating text-right"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <span class="rated">Rated 4.0/5</span> </div>*@
                    </div>
                </div>
            </figcaption>
            <div class="bottom-wrap-payment">
                <figcaption class="info-wrap">
                    <div class="row">
                        <div class="col-md-9 col-xs-9">
                            <a href="#" class="title" data-abc="true"><i class="fas fa-lira-sign"></i>@Model.Price</a> <span class="rated"></span>
                        </div>

                    </div>
                </figcaption>
            </div>
            <div class="text-center  mb-3">
                <a asp-controller="Shop" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-outline-dark btn-primary btn-sm " style="border-radius:25px"><i class="fa fa-info-circle text-white"></i> Ürün Detay</a>

                @if (User.Identity.IsAuthenticated)
                {
                    <form asp-controller="Cart" asp-action="AddToCart" method="post" style="display:inline;">
                        <input type="hidden" name="productId" value="@Model.Id" />
                        <input type="hidden" name="quantity" value="1" />
                        <button type="submit" class="btn btn-outline-dark btn-primary btn-sm ml-3" style="border-radius:25px"><i class="fa fa-shopping-cart text-white"></i> Sepete Ekle</button>
                    </form>
                }
            </div>
        </figure>
    </div>
    </div>

Güncel 2.2/ShopApp/ShopApp.WebUI/Views/Shared/_slider.cshtml
<div id="carouselExampleControls" class="carousel slide mb-5" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/User/images/slide1-01.jpg" class="d-block w-100" alt="...">
            @*<div class="carousel-caption d-none d-md-block">
                <h1 class="text-white mb-5">First slide label</h1>
                <p class="text-white mb-5">Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
            </div>*@
        </div>
        <div class="carousel-item">
            <img src="~/User/images/slide1-02.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/User/images/slide1-03.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

    
    
    
    @*<partial name="_search" />*@
    <!--<div class="hero__item set-bg" data-setbg="~/User/img/hero/banner.jpg">
        <div class="hero__text">
            <span>GUVENLI ALISVERIS</span>
            <h2>Kaliteli <br />100% Yerli</h2>
            <p>Hızlı Kargo Imkani Ile</p>
            <a asp-controller="Shop" asp-action="List" class="primary-btn">Alışveriş Zamanı!</a>
        </div>
    </div>-->